language: ruby
rvm: 2.3.0
before_script:
- travis_retry bundle install
script: bundle exec jekyll build
branches:
  only:
  - master
  - "/^v\\d+\\./"
after_success:
- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then echo running deploy; fi
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#rubinius
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    urls:
      secure: H8yt+D9boWjHalkLQ1xqm8gZoRlVVqCcTS2fdEen5LpYf9afFv1a7lnuIK8XgYUn+OnKvwrsNIafDIl6DcZLiL491y7+MisFGTdD91yuRAc0J44tXXPdAVBCTqtOqof4trq67vQGm1L+iWS6ZqaXT/jSCmUA1AbxY0c/+UnM9h8=
    on_success: always
    on_failure: always
    on_start: always
